#!/usr/bin/env python3
"""design-generate skill — 视觉生产环节。

Pipeline:
  1. 从 Plan 读取 direction，或通过 --prompt 手动输入
  2. 读取 manifest 获取参考图
  3. 调用 Lovart 生图（live 模式）或生成 mock 占位图（dry-run）
  4. 输出 Visual 实体（.md + .jsonl）
  5. 写入 manifest.jsonl 记录生图元数据
  6. 输出保存到 90_Runs/<run_id>/outputs/

为后续 critic_visual.py 和 archive_design.py 预留字段。
标准库 + PyYAML 即可运行。
"""

from __future__ import annotations

import argparse
import hashlib
import json
import secrets
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

_HERE = Path(__file__).resolve().parent
_SKILL_ROOT = _HERE.parent
if str(_SKILL_ROOT) not in sys.path:
    sys.path.insert(0, str(_SKILL_ROOT))

from shared import (  # noqa: E402
    frontmatter, manifest as manifest_mod, plan_loader, schema,
)
from shared.lovart_hook import LovartHook, LovartError


SKILL_VERSION = "0.1.0"


def _now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _make_run_id(now: datetime) -> str:
    return f"run_generate_{now:%Y%m%d_%H%M%S}_{secrets.token_hex(2)}"


def _make_visual_id(now: datetime) -> str:
    return f"vis_{now:%Y%m%d_%H%M%S}_{secrets.token_hex(3)}"


def _canonical_hash(obj: Any) -> str:
    payload = json.dumps(obj, sort_keys=True, ensure_ascii=False, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# Build Visual entity
# ---------------------------------------------------------------------------

def build_visual_fm(
    *,
    visual_id: str,
    run_id: str,
    plan_id: str | None,
    direction_id: str | None,
    asset_ids: list[str],
    generation_result: dict[str, Any],
    llm_mode: str,
    style_description: str,
    now: str,
) -> dict[str, Any]:
    return {
        "id": visual_id,
        "type": "visual",
        "schema_version": "1.0",
        "created_at": now,
        "updated_at": now,
        "status": "draft",
        "created_by": "skill:design-generate",
        "source_run_id": run_id,
        "source_plan_id": plan_id,
        "source_direction_id": direction_id,
        "asset_ids": asset_ids,
        "generated_at": now,
        "llm_mode": llm_mode,
        "generator": generation_result.get("model", "mock"),
        "model": generation_result.get("model", "mock"),
        "image_path": generation_result["image_path"],
        "image_hash": generation_result["image_hash"],
        "image_size_bytes": generation_result["image_size_bytes"],
        "output_format": generation_result.get("output_format", "png"),
        "prompt_used": generation_result.get("prompt_used", ""),
        "style_description": style_description,
        "consumed_patterns": [],  # P2
        "metadata": generation_result.get("metadata", {}),
        # Reserved for future critic_visual.py
        "critique_id": None,
        "critique_score": None,
        # Reserved for future archive_design.py
        "derived_pattern_id": None,
    }


def visual_note_body(fm: dict[str, Any]) -> str:
    lines = [
        f"# Visual · {fm['id']}",
        "",
        f"- Status: {fm['status']}",
        f"- Generator: {fm['generator']} ({fm['model']})",
        f"- LLM mode: {fm['llm_mode']}",
        f"- Style: {fm['style_description']}",
        "",
        "## Prompt",
        fm["prompt_used"],
        "",
        "## Image",
        f"- Path: `{fm['image_path']}`",
        f"- Hash: `{fm['image_hash'][:16]}...`",
        f"- Size: {fm['image_size_bytes']} bytes",
        f"- Format: {fm['output_format']}",
        "",
        "## Provenance",
    ]
    if fm.get("source_plan_id"):
        lines.append(f"- Plan: [[{fm['source_plan_id']}]]")
    if fm.get("source_direction_id"):
        lines.append(f"- Direction: {fm['source_direction_id']}")
    if fm.get("asset_ids"):
        lines.append(f"- Assets: {', '.join(fm['asset_ids'])}")
    lines.append("")
    meta = fm.get("metadata") or {}
    if meta:
        lines.append("## Metadata")
        for k, v in meta.items():
            lines.append(f"- {k}: {v}")
        lines.append("")
    lines.append("---")
    lines.append(f"_Generated by design-generate v{SKILL_VERSION} at {fm['created_at']}_")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Build Run record
# ---------------------------------------------------------------------------

def build_run_fm(
    *,
    run_id: str,
    started: datetime,
    finished: datetime,
    inputs: dict[str, Any],
    visual_id: str,
    visual_path: Path,
    manifest_path: Path,
    llm_mode: str,
    metrics: dict[str, Any],
    errors: list[dict[str, Any]],
    outcome: str,
) -> dict[str, Any]:
    started_iso = started.replace(microsecond=0).isoformat().replace("+00:00", "Z")
    finished_iso = finished.replace(microsecond=0).isoformat().replace("+00:00", "Z")
    duration_ms = int((finished - started).total_seconds() * 1000)
    return {
        "id": run_id,
        "type": "run",
        "schema_version": "1.0",
        "created_at": started_iso,
        "updated_at": finished_iso,
        "status": "active",
        "created_by": "skill:design-generate",
        "source_run_id": None,
        "tags": ["run", "generate"],
        "skill": "design-generate",
        "skill_version": SKILL_VERSION,
        "started_at": started_iso,
        "finished_at": finished_iso,
        "duration_ms": duration_ms,
        "outcome": outcome,
        "parent_run_id": None,
        "project_id": inputs.get("project_id", ""),
        "inputs": inputs,
        "inputs_hash": _canonical_hash(inputs),
        "rules_used": [],
        "prompts_used": [],
        "outputs": [
            {"kind": "file", "path": str(visual_path), "role": "primary"},
            {"kind": "entity", "entity_id": visual_id, "action": "created"},
            {"kind": "file", "path": str(manifest_path), "role": "metadata"},
        ],
        "entities_created": [visual_id],
        "entities_updated": [],
        "metrics": metrics,
        "errors": errors,
        "decision": None,
        "next_eligible_skill": "design-critic-visual",
    }


def run_note_body(fm: dict[str, Any]) -> str:
    m = fm["metrics"]
    return (
        f"# Run · design-generate · {fm['started_at']}\n\n"
        f"- Outcome: {fm['outcome']}\n"
        f"- Duration: {fm['duration_ms']} ms\n"
        f"- Visual created: {fm['entities_created'][0]}\n"
        f"- LLM mode: {m.get('llm_mode', '')}\n"
        f"- Model: {m.get('model', '')}\n"
        f"- Image size: {m.get('image_size_bytes', 0)} bytes\n"
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="design-generate skill — 视觉生产环节。",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--plan", help="Path to plan .md (可选，与 --prompt 二选一)")
    parser.add_argument("--direction", help="Direction ID from plan (需配合 --plan)")
    parser.add_argument("--prompt", help="Manual prompt text (与 --plan 二选一)")
    parser.add_argument("--manifest", help="Path to asset manifest.jsonl")
    parser.add_argument("--asset-ids", nargs="*", help="Explicit asset IDs to use as reference images")
    parser.add_argument("--out", required=True, help="Output directory for Visual and Run records")
    parser.add_argument("--style", default="", help="Style description tag")
    parser.add_argument("--model", default="generate_image_seedream_v4_5", help="Lovart model name")
    parser.add_argument("--llm", choices=["dry-run", "live"], default="dry-run",
                        help="LLM mode (default: dry-run)")
    parser.add_argument("--output-format", choices=["png", "jpeg", "webp"], default="png")
    parser.add_argument("--strict", action="store_true",
                        help="Abort on schema validation failure")
    args = parser.parse_args()

    # Validate input mode
    if not args.plan and not args.prompt:
        print("ERROR: provide either --plan (with optional --direction) or --prompt", file=sys.stderr)
        return 2
    if args.plan and args.prompt:
        print("WARNING: both --plan and --prompt provided, --prompt takes precedence", file=sys.stderr)

    started = datetime.now(timezone.utc)
    started_perf = time.perf_counter()
    run_id = _make_run_id(started)

    out_dir = Path(args.out).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    errors: list[dict[str, Any]] = []

    # --- Determine prompt and reference images ---
    prompt_text = ""
    plan_id: str | None = None
    direction_id: str | None = None
    project_id: str = ""
    style_desc = args.style or ""

    if args.prompt:
        prompt_text = args.prompt
        style_desc = args.style or "(manual prompt)"
    elif args.plan:
        plan_path = Path(args.plan).expanduser().resolve()
        try:
            plan = plan_loader.load_plan(plan_path)
            plan_id = plan.id
            project_id = plan.project_id

            if args.direction:
                d = plan.get_direction(args.direction)
                if not d:
                    available = [dd["id"] for dd in plan.directions]
                    print(f"ERROR: direction {args.direction!r} not found. Available: {available}",
                          file=sys.stderr)
                    return 2
                direction_id = d["id"]
                # Build prompt from direction
                prompt_text = (
                    f"{d.get('core_idea', '')}\n"
                    f"Visual approach: {d.get('visual_approach', '')}\n"
                    f"Rationale: {d.get('rationale', '')}"
                ).strip()
                style_desc = args.style or d.get("name", "")
            else:
                # Use first direction
                if plan.directions:
                    d = plan.directions[0]
                    direction_id = d["id"]
                    prompt_text = (
                        f"{d.get('core_idea', '')}\n"
                        f"Visual approach: {d.get('visual_approach', '')}"
                    ).strip()
                    style_desc = args.style or d.get("name", "")
                else:
                    print("ERROR: plan has no directions", file=sys.stderr)
                    return 2
        except plan_loader.PlanLoadError as exc:
            print(f"ERROR: failed to load plan: {exc}", file=sys.stderr)
            return 2

    if not prompt_text:
        print("ERROR: prompt is empty", file=sys.stderr)
        return 2

    # --- Load manifest for reference images ---
    ref_images: list[str] = []
    asset_ids: list[str] = []

    if args.manifest:
        try:
            manifest = manifest_mod.load_manifest(Path(args.manifest).expanduser().resolve())
        except manifest_mod.ManifestReadError as exc:
            print(f"ERROR: failed to load manifest: {exc}", file=sys.stderr)
            return 2

        if args.asset_ids:
            asset_ids = args.asset_ids
        else:
            asset_ids = manifest.all_ids()

        records = manifest.by_ids(asset_ids)
        ref_images = [r.get("source_path", "") for r in records if r.get("source_path")]
        # Filter to existing files
        ref_images = [p for p in ref_images if Path(p).exists()]

    # --- Generate ---
    hook = LovartHook(output_dir=str(out_dir))

    if args.llm == "dry-run":
        gen_result = hook._generate_mock(
            prompt=prompt_text,
            output_format=args.output_format,
        )
        llm_mode = "dry-run"
    elif args.llm == "live":
        if not hook.configured:
            print("ERROR: live mode requires LOVART_ACCESS_KEY and LOVART_SECRET_KEY env vars",
                  file=sys.stderr)
            return 2
        try:
            gen_result = hook.generate_image(
                prompt=prompt_text,
                reference_images=ref_images if ref_images else None,
                model=args.model,
                output_format=args.output_format,
            )
        except LovartError as exc:
            errors.append({"level": "error", "code": "lovart_generation_failed",
                          "target": "", "message": str(exc)})
            print(f"ERROR: Lovart generation failed: {exc}", file=sys.stderr)
            return 1
        llm_mode = "live"
    else:
        print(f"ERROR: unsupported llm mode {args.llm!r}", file=sys.stderr)
        return 2

    # --- Build Visual entity ---
    now_str = _now_iso()
    visual_id = _make_visual_id(started)
    visual_fm = build_visual_fm(
        visual_id=visual_id,
        run_id=run_id,
        plan_id=plan_id,
        direction_id=direction_id,
        asset_ids=asset_ids,
        generation_result=gen_result,
        llm_mode=llm_mode,
        style_description=style_desc,
        now=now_str,
    )

    # --- Validate ---
    try:
        schema.validate(visual_fm, "visual")
    except schema.SchemaError as exc:
        errors.append({"level": "error" if args.strict else "warning",
                       "code": "visual_schema_invalid", "target": visual_id, "message": str(exc)})
        if args.strict:
            print(f"ERROR: visual schema invalid: {exc}", file=sys.stderr)
            return 4

    # --- Write Visual ---
    visual_md_path = out_dir / f"{visual_id}.md"
    frontmatter.write(visual_md_path, visual_fm, visual_note_body(visual_fm))

    visual_jsonl_path = out_dir / f"{visual_id}.jsonl"
    visual_jsonl_path.write_text(
        json.dumps(visual_fm, ensure_ascii=False) + "\n", encoding="utf-8"
    )

    # --- Write generation manifest (per-run metadata) ---
    gen_manifest = {
        "run_id": run_id,
        "visual_id": visual_id,
        "timestamp": now_str,
        "prompt": prompt_text,
        "model": gen_result.get("model", ""),
        "llm_mode": llm_mode,
        "input_images": ref_images,
        "output_url": gen_result["image_path"],
        "thread_id": gen_result.get("metadata", {}).get("thread_id"),
        "image_hash": gen_result["image_hash"],
        "image_size_bytes": gen_result["image_size_bytes"],
        "asset_ids": asset_ids,
        "plan_id": plan_id,
        "direction_id": direction_id,
    }
    manifest_out_path = out_dir / "manifest.jsonl"
    manifest_out_path.write_text(
        json.dumps(gen_manifest, ensure_ascii=False) + "\n", encoding="utf-8"
    )

    # --- Build Run record ---
    finished = datetime.now(timezone.utc)
    metrics = {
        "llm_mode": llm_mode,
        "model": gen_result.get("model", ""),
        "image_size_bytes": gen_result.get("image_size_bytes", 0),
        "reference_images_count": len(ref_images),
        "asset_count": len(asset_ids),
        "elapsed_perf_seconds": round(time.perf_counter() - started_perf, 4),
        "execution_flow": [
            {"phase": "pre-check", "principle": "Think",
             "check": "decompose task inputs and establish verification criteria"},
            {"phase": "execution", "principle": "Surgical",
             "check": "make the smallest scoped change needed for the run"},
            {"phase": "post-check", "principle": "Verify",
             "check": "validate generated entities and run pytest for repository changes"},
        ],
    }

    inputs = {
        "project_id": project_id,
        "plan_path": str(Path(args.plan).expanduser().resolve()) if args.plan else None,
        "direction_id": direction_id,
        "manifest_path": str(Path(args.manifest).expanduser().resolve()) if args.manifest else None,
        "asset_ids": asset_ids,
        "prompt_length": len(prompt_text),
        "style": style_desc,
        "model": args.model,
        "output_format": args.output_format,
        "llm_mode": args.llm,
    }

    has_error = any(e.get("level") == "error" for e in errors)
    outcome = "failure" if has_error else ("partial" if errors else "success")

    run_fm = build_run_fm(
        run_id=run_id,
        started=started,
        finished=finished,
        inputs=inputs,
        visual_id=visual_id,
        visual_path=visual_md_path,
        manifest_path=manifest_out_path,
        llm_mode=llm_mode,
        metrics=metrics,
        errors=errors,
        outcome=outcome,
    )
    try:
        schema.validate(run_fm, "run")
    except schema.SchemaError as exc:
        print(f"WARNING: run record failed schema validation: {exc}", file=sys.stderr)

    run_path = out_dir / f"{run_id}.md"
    frontmatter.write(run_path, run_fm, run_note_body(run_fm))

    # --- Summary ---
    print(f"Run id:           {run_id}")
    print(f"Visual id:        {visual_id}")
    if plan_id:
        print(f"Plan:             {plan_id}")
    if direction_id:
        print(f"Direction:        {direction_id}")
    print(f"LLM mode:         {llm_mode}")
    print(f"Model:            {gen_result.get('model', '')}")
    print(f"Reference images: {len(ref_images)}")
    print(f"Assets:           {len(asset_ids)}")
    print(f"Image:            {gen_result['image_path']}")
    print(f"Image size:       {gen_result['image_size_bytes']} bytes")
    print(f"Image hash:       {gen_result['image_hash'][:16]}...")
    print(f"Outcome:          {outcome}")
    print(f"  visual:  {visual_md_path}")
    print(f"  manifest:{manifest_out_path}")
    print(f"  run:     {run_path}")
    if errors:
        print(f"  warnings/errors: {len(errors)}")

    return 0 if outcome != "failure" else 1


if __name__ == "__main__":
    raise SystemExit(main())
